// src/components/typing.jsx
import Typewriter from 'typewriter-effect';

export const Typing = () => {
  return (
    <div className="text-white text-6xl px-3">
      <Typewriter
        options={{
          strings: ['Mobile', 'Web'],
          autoStart: true,
          loop: true,
          delay: 75, // typing speed in ms
          deleteSpeed: 50,
          pauseFor: 2000, // pause before deleting
        }}
      />
    </div>
  );
};

// src/components/Typing.vue
<script setup>
import { onMounted } from 'vue';
import Typewriter from 'typewriter-effect/dist/core';

onMounted(() => {
  new Typewriter('#typewriter-vue', {
    strings: ['Mobile', 'Web'],
    autoStart: true,
    loop: true,
    delay: 75,
    deleteSpeed: 50,
  });
});
</script>

<template>
  <div id="typewriter-vue" class="text-white text-6xl px-3"></div>
</template>
